---
name: "run_ansible_playbook"
description: "Custom run ansible-playbook"
runner_type: "local-shell-cmd"
entry_point: ""
enabled: true
parameters:
  sudo:
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  timeout:
    default: 6000
  cmd:
    description: "Command to run"
    immutable: true
    default: "/usr/local/bin/ansible-playbook --inventory-file=/opt/omnia/plugins/inventory {{playbook}}"
  playbook:
    description: "playbook"
    type: string
  inventory_file:
    description: "inventory_file"
    type: string
 