---
- name: Update package on remote hosts, run on 25% of servers at a time
  hosts: "{{ hosts }}"
  serial: "25%"
  sudo: yes
  tasks:
    - name: Check if Package is installed
      command: dpkg-query -l {{ package }}
      register: is_installed
      failed_when: is_installed.rc > 1
      changed_when: no

    - name: Update Package only if installed
      apt: name={{ package }}
        state=latest
        update_cache=yes
      when: is_installed.rc == 0
